### ISSUE TITLE
form group isn't necessarily field.parent()

### ISSUE THREAD

**Issue by jmp909** [whipsterCZ/laravel-ajax#2]
hi,

i think this might be better if it get's the closest `form-group` rather than parent?
https://github.com/whipsterCZ/laravel-ajax/blob/master/app/Services/Ajax/laravel.ajax.js#L258

`var formGroup = field.parent()`

my code is like this:
```html
<div class="form-group c-form-group--firstname row"><!-- has-error should be here -->
  <label for="firstname" class="col-xs-3 control-label">First name:</label>
  <div class="col-xs-9">
    <input class="form-control" placeholder="First name" maxlength="35" name="firstname" 
    type="text" value="whatever" id="firstname" aria-describedby="firstname-error">
    <span id="firstname-error" class="form-error-text" style="display: none;"></span>
  </div>
</div>
```
as you can see, form-group is the grandparent to my field.

so something like this may cover more situations
`var formGroup = field.closest('.form-group')`

thanks
J

**Comment by whipsterCZ** [comment]
i added heuristics 

Library will use closest `.form-group` or  `parent()` if form-group is not exists

**Comment by whipsterCZ** [comment]
could you test if its working as excpected?

**Comment by jmp909** [comment]
Hi, 

sounds good thanks I'll try and find an old project with this in it.

J
